apiVersion: v2
name: hazelcastplatform
description: A Helm chart for deploying a simple Hazelcast cluster on Kubernetes.

type: application

version: 2.2.0

# Version of Hazelcast Platform used in this chart
appVersion: "5.6.0"

# Useful commands: 
# helm upgrade --install hazelcastwithmancenter ./hazelcastwithmancenter --namespace=hazelcastplatform --create-namespace
# helm uninstall hazelcastwithmancenter --namespace=hazelcastplatform
